# Generated by Django 5.2.12 on 2026-04-09 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaivarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='first/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ml', 'masala'), ('gr', 'ginger'), ('el', 'elichi'), ('ma', 'macha')], max_length=2)),
            ],
        ),
    ]
