# Generated by Django 5.2.12 on 2026-04-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='descriptions',
            field=models.TextField(default=''),
        ),
    ]
