# Generated by Django 5.2.12 on 2026-04-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_order_profile_review_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='date_added',
            new_name='date_opened',
        ),
    ]
